[package]
name = "beer-thirty-worker"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-unknown-unknown"

[lib]
name = "lib"
path = "b30/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = "z"

[features]
build-binary = ["clap"]

[[bin]]
name = "test-tool"
path = "b30/tool.rs"
required-features = ["build-binary"]

[dependencies]
chrono = "0.4.38"
clap = { version = "4.0", features = ["derive"], optional = true }
futures = "0.3"
regex = { version = "1.11.1", default-features = false, features = ["std"] }
polars-core = "0.34.2"
serde_json = "1.0"
soup = "0.5"
tokio = { version = "1.41.1", default-features = false, features = ["macros"] }
worker = "0.4.2"
url = "2.3"
