[package]
name = "beer-thirty-worker"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-unknown-unknown"

[lib]
name = "lib"
path = "b30/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = "z"

#[[bin]]
#name = "test-tool"
#path = "b30/tool.rs"

[dependencies]
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
futures = "0.3"
regex = "1.11.1"
polars-core = "*"
polars-lazy = "*"
getrandom = { version = "*", features = ["js"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
soup = "0.5"
tokio = { version = "1.0", features = ["sync", "macros", "rt"] }
worker = "0.4.2"
url = "2.3"
