[package]
name = "beer-thirty-worker"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm32-unknown-unknown"

[lib]
name = "lib"
path = "b30/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = "z"

[dependencies]
chrono = "0.4.38"
futures = "0.3"
regex = { version = "1.11.1", default-features = false, features = ["std", "unicode-perl"] }
polars-core = "0.34.2"
serde_json = "1.0"
tokio = { version = "1.41.1", default-features = false, features = ["macros", "rt"] }
worker = "0.4.2"
worker-kv = "0.7.0"
url = "2.3"
