[package]
name = "beer-thirty-worker"
version = "0.1.0"
edition = "2021"

[lib]
name = "lib"
path = "b30/lib.rs"

[[bin]]
name = "test-tool"
path = "b30/tool.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
regex = "1.11.1"
reqwest = { version = "0.11", features = ["json"] }
soup = "0.5"
tokio = { version = "1.0", features = ["full"] }
url = "2.3"
